### ISSUE TITLE
A conscious decision to keep Jade attributes comma separated?

### ISSUE THREAD

**Issue by juice49** [andyet/yeti-guide#9]
I enjoyed reading your style guide!

I'm curious whether the decision to keep Jade attributes comma separated was a conscious one? Your examples all follow this style, but there isn't an explanation. I dropped commas from my Jade as soon as the parser supported, which is cleaner IMO, it'd be interesting to know if you have reasons for/against.

(Sorry, I don't think I can tag this as a question because I'm not a contributor).

Thanks!

**Comment by thefoxis** [comment]
Hey Ash!

Glad you've enjoyed it. Honestly there's no deeper reasoning here. I've started writing Stylus prior to the amendment of the parser in 2013 and the pattern just carried through. I agree that for parity with HTML they could be dropped, although in my opinion they somewhat improve readability more than just a space. 

Thanks for the suggestion :)

**Comment by juice49** [comment]
I see, interesting. Thanks for replying (: I know y'all busy people!
